openapi: "3.0.2"
info:
  version: 1.0.1
  title: Wine Quality Simple Project
servers:
  - url: http://localhost:4001
paths:
  /:
    get:
      description: Greeting
      responses:
        '200':
          description: Greeting response
          content:
            text/html:
              schema:
                type: string
  /predict:
    post:
      description: Returns model response based on input parameters
      requestBody:
        description: JSON with input parameters
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Model response
          content:
            application/json:
              schema:
                type: array
