openapi: "3.0.2"
info:
  version: 1.0.1
  title: Wine Quality Simple Project
servers:
  - url: http://localhost:4001
paths:
  /:
    get:
      description: Greeting
      responses:
        '200':
          description: Greeting response
          content:
            text/html:
              schema:
                type: string
  /predict:
    post:
      description: Returns model response based on input parameters
      requestBody:
        description: JSON with input parameters
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  fixed acidity:
                    type: number
                  volatile acidity:
                    type: number
                  citric acid:
                    type: number
                  residual sugar:
                    type: number
                  chlorides:
                    type: number
                  free sulfur dioxide:
                    type: int32
                  total sulfur dioxide:
                    type: int32
                  density:
                    type: number
                  pH:
                    type: number
                  sulphates:
                    type: number
                  alcohol:
                    type: int32
                required:
                  - fixed acidity
                  - volatile acidity
                  - citric acid
                  - residual sugar
                  - chlorides
                  - free sulfur dioxide
                  - total sulfur dioxide
                  - density
                  - pH
                  - sulphates
                  - alcohol
      responses:
        '200':
          description: Model response
          content:
            application/json:
              schema:
                type: array
